/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as IndustriesPlumbersRouteImport } from './routes/industries/plumbers'
import { Route as IndustriesLawFirmsRouteImport } from './routes/industries/law-firms'
import { Route as IndustriesHvacRouteImport } from './routes/industries/hvac'
import { Route as IndustriesDentistsRouteImport } from './routes/industries/dentists'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesPlumbersRoute = IndustriesPlumbersRouteImport.update({
  id: '/industries/plumbers',
  path: '/industries/plumbers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesLawFirmsRoute = IndustriesLawFirmsRouteImport.update({
  id: '/industries/law-firms',
  path: '/industries/law-firms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHvacRoute = IndustriesHvacRouteImport.update({
  id: '/industries/hvac',
  path: '/industries/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesDentistsRoute = IndustriesDentistsRouteImport.update({
  id: '/industries/dentists',
  path: '/industries/dentists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/industries/dentists': typeof IndustriesDentistsRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/law-firms': typeof IndustriesLawFirmsRoute
  '/industries/plumbers': typeof IndustriesPlumbersRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/industries/dentists': typeof IndustriesDentistsRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/law-firms': typeof IndustriesLawFirmsRoute
  '/industries/plumbers': typeof IndustriesPlumbersRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/industries/dentists': typeof IndustriesDentistsRoute
  '/industries/hvac': typeof IndustriesHvacRoute
  '/industries/law-firms': typeof IndustriesLawFirmsRoute
  '/industries/plumbers': typeof IndustriesPlumbersRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/industries/dentists'
    | '/industries/hvac'
    | '/industries/law-firms'
    | '/industries/plumbers'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/industries/dentists'
    | '/industries/hvac'
    | '/industries/law-firms'
    | '/industries/plumbers'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/industries/dentists'
    | '/industries/hvac'
    | '/industries/law-firms'
    | '/industries/plumbers'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  IndustriesDentistsRoute: typeof IndustriesDentistsRoute
  IndustriesHvacRoute: typeof IndustriesHvacRoute
  IndustriesLawFirmsRoute: typeof IndustriesLawFirmsRoute
  IndustriesPlumbersRoute: typeof IndustriesPlumbersRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/plumbers': {
      id: '/industries/plumbers'
      path: '/industries/plumbers'
      fullPath: '/industries/plumbers'
      preLoaderRoute: typeof IndustriesPlumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/law-firms': {
      id: '/industries/law-firms'
      path: '/industries/law-firms'
      fullPath: '/industries/law-firms'
      preLoaderRoute: typeof IndustriesLawFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/hvac': {
      id: '/industries/hvac'
      path: '/industries/hvac'
      fullPath: '/industries/hvac'
      preLoaderRoute: typeof IndustriesHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/dentists': {
      id: '/industries/dentists'
      path: '/industries/dentists'
      fullPath: '/industries/dentists'
      preLoaderRoute: typeof IndustriesDentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  IndustriesDentistsRoute: IndustriesDentistsRoute,
  IndustriesHvacRoute: IndustriesHvacRoute,
  IndustriesLawFirmsRoute: IndustriesLawFirmsRoute,
  IndustriesPlumbersRoute: IndustriesPlumbersRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
